import { View, Text, ScrollView, TouchableOpacity, ActivityIndicator, TextInput, Alert, Dimensions } from 'react-native';
import { useState, useEffect } from 'react';
import { LiveService } from '../../lib/services';
import { supabase } from '../../lib/supabase';
import { FontAwesome } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as Clipboard from 'expo-clipboard';
import Animated, { FadeInDown, FadeInUp, Layout } from 'react-native-reanimated';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function LaTeXBuilderScreen() {
  const [resumes, setResumes] = useState<any[]>([]);
  const [apps, setApps] = useState<any[]>([]);
  const [selectedResume, setSelectedResume] = useState<any>(null);
  const [selectedApp, setSelectedApp] = useState<any>(null);
  
  const [latex, setLatex] = useState('');
  const [explanation, setExplanation] = useState('');
  const [loading, setLoading] = useState(false);
  const [mode, setMode] = useState<'setup' | 'editor'>('setup');

  useEffect(() => {
    async function fetchData() {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const [res, applications] = await Promise.all([
          supabase.from('resumes').select('*').eq('user_id', user.id),
          supabase.from('applications').select('*').eq('user_id', user.id).order('created_at', { ascending: false })
        ]);
        setResumes(res.data || []);
        setApps(applications.data || []);
      }
    }
    fetchData();
  }, []);

  const handleGenerate = async () => {
    if (!selectedResume || !selectedApp) {
      Alert.alert('Selection Required', 'Please select both a resume and a target job scan.');
      return;
    }
    setLoading(true);
    try {
      const res = await LiveService.generateTailoredLaTeX(selectedResume.raw_text, selectedApp.job_description);
      setLatex(res.latex);
      setExplanation(res.explanation);
      setMode('editor');
    } catch (e) {
      Alert.alert('Error', 'Failed to generate tailored resume.');
    }
    setLoading(false);
  };

  const handleCopyToClipboard = async () => {
    await Clipboard.setStringAsync(latex);
    Alert.alert('Copied!', 'LaTeX source code copied to clipboard for Overleaf.');
  };

  const handleSaveToVault = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
          const { error } = await supabase.from('resumes').insert({
              user_id: user.id,
              name: `Tailored: ${selectedApp.company_name} - ${selectedApp.role}`,
              raw_text: latex,
              is_default: false
          });
          if (error) Alert.alert('Error', 'Failed to save to vault.');
          else Alert.alert('Success', 'Tailored LaTeX saved to your Resume Vault.');
      }
  };

  const generatePDF = async () => {
    // Basic Elite Tech HTML Template mimicking LaTeX
    const html = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', 'Arial', sans-serif; padding: 40px; color: #333; line-height: 1.5; }
            h1 { text-align: center; font-size: 24pt; margin-bottom: 5px; text-transform: uppercase; letter-spacing: 2px; }
            .contact { text-align: center; font-size: 10pt; color: #666; margin-bottom: 30px; border-bottom: 1px solid #eee; padding-bottom: 20px; }
            h2 { border-bottom: 1px solid #333; font-size: 14pt; padding-bottom: 5px; margin-top: 25px; margin-bottom: 15px; text-transform: uppercase; }
            .item { margin-bottom: 15px; }
            .item-header { display: flex; justify-content: space-between; font-weight: bold; }
            .bullets { margin-top: 5px; padding-left: 20px; }
            .bullets li { margin-bottom: 5px; font-size: 10.5pt; }
          </style>
        </head>
        <body>
          <h1>${selectedResume.name.replace(/[^a-zA-Z]/g, ' ').trim() || 'Candidate Name'}</h1>
          <div class="contact">Email: user@example.com | Phone: +1 234 567 890 | Location: New York, NY</div>
          
          <h2>Optimization Summary</h2>
          <p style="font-size: 10.5pt; font-style: italic; color: #444;">${explanation}</p>

          <h2>Experience & Projects (Tailored)</h2>
          <div class="item">
             <p style="font-size: 10.5pt;">${latex.substring(0, 1000).replace(/\\/g, '').replace(/\{/g, '').replace(/\}/g, '')}...</p>
          </div>

          <p style="font-size: 8pt; color: #999; margin-top: 50px; text-align: center;">Generated by HireSight Intelligence Platform</p>
        </body>
      </html>
    `;
    
    try {
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri);
    } catch (e) {
      Alert.alert('Error', 'Failed to generate PDF.');
    }
  };

  if (mode === 'editor') {
    return (
        <SafeAreaView className="flex-1 bg-background">
            <View className="flex-1 p-6">
                <View className="flex-row items-center justify-between mb-6">
                    <TouchableOpacity onPress={() => setMode('setup')}>
                        <FontAwesome name="arrow-left" size={20} color="#3B82F6" />
                    </TouchableOpacity>
                    <Text className="text-white font-bold text-lg">AI LaTeX Editor</Text>
                    <TouchableOpacity onPress={handleSaveToVault}>
                         <FontAwesome name="cloud-upload" size={20} color="#10B981" />
                    </TouchableOpacity>
                </View>

                <View className="bg-slate-900 rounded-3xl p-5 mb-4 border border-slate-800">
                    <Text className="text-blue-400 font-bold text-xs uppercase tracking-widest mb-2">AI Optimization Logic</Text>
                    <Text className="text-slate-400 text-xs leading-5 italic">{explanation}</Text>
                </View>

                <TextInput 
                    value={latex}
                    onChangeText={setLatex}
                    multiline
                    textAlignVertical="top"
                    className="flex-1 bg-black/40 border border-slate-800 rounded-3xl p-5 text-slate-300 font-mono text-xs leading-5 mb-6"
                />

                <View className="flex-row gap-4 mb-6">
                    <TouchableOpacity 
                        onPress={handleCopyToClipboard}
                        className="flex-1 bg-slate-800 h-14 rounded-2xl flex-row items-center justify-center border border-slate-700"
                    >
                        <FontAwesome name="copy" size={16} color="#94A3B8" className="mr-3" />
                        <Text className="text-slate-300 font-bold">Copy Source</Text>
                    </TouchableOpacity>
                    <TouchableOpacity 
                        onPress={generatePDF}
                        className="flex-1 bg-blue-600 h-14 rounded-2xl flex-row items-center justify-center shadow-lg"
                    >
                        <FontAwesome name="file-pdf-o" size={16} color="white" className="mr-3" />
                        <Text className="text-white font-bold">Export PDF</Text>
                    </TouchableOpacity>
                </View>
            </View>
        </SafeAreaView>
    );
  }

  return (
    <SafeAreaView className="flex-1 bg-background">
      <ScrollView className="flex-1 p-6" showsVerticalScrollIndicator={false}>
        <Animated.View entering={FadeInDown.duration(600)} className="mb-8 mt-4">
          <Text className="text-4xl font-bold text-white tracking-tight italic">LaTeX Hub</Text>
          <Text className="text-slate-400 mt-1">Automated elite resume tailoring for Overleaf.</Text>
        </Animated.View>

        <View className="space-y-6">
            <View>
                <Text className="text-xs font-black text-slate-500 uppercase tracking-widest mb-4 ml-1">1. Select Base Resume</Text>
                <ScrollView horizontal showsHorizontalScrollIndicator={false} className="flex-row gap-3">
                    {resumes.map(r => (
                        <TouchableOpacity 
                            key={r.id}
                            onPress={() => setSelectedResume(r)}
                            className={`px-6 py-4 rounded-[28px] border ${selectedResume?.id === r.id ? 'bg-blue-600 border-blue-500 shadow-lg shadow-blue-500/20' : 'bg-slate-900 border-slate-800'}`}
                        >
                            <Text className={`font-bold ${selectedResume?.id === r.id ? 'text-white' : 'text-slate-400'}`}>{r.name}</Text>
                        </TouchableOpacity>
                    ))}
                </ScrollView>
            </View>

            <View>
                <Text className="text-xs font-black text-slate-500 uppercase tracking-widest mb-4 ml-1">2. Target Job Scan</Text>
                <View className="space-y-3">
                    {apps.map(app => (
                        <TouchableOpacity 
                            key={app.id}
                            onPress={() => setSelectedApp(app)}
                            className={`p-5 rounded-[32px] border flex-row items-center justify-between ${selectedApp?.id === app.id ? 'bg-blue-600/10 border-blue-500' : 'bg-slate-900 border-slate-800'}`}
                        >
                            <View>
                                <Text className={`font-bold text-base ${selectedApp?.id === app.id ? 'text-white' : 'text-slate-300'}`}>{app.company_name}</Text>
                                <Text className="text-slate-500 text-xs">{app.role}</Text>
                            </View>
                            <View className="items-end">
                                <Text className="text-blue-500 font-black text-xs">{app.ats_score}% Score</Text>
                                <Text className="text-[10px] text-slate-600 mt-1 uppercase font-bold">{new Date(app.created_at).toLocaleDateString()}</Text>
                            </View>
                        </TouchableOpacity>
                    ))}
                </View>
            </View>
        </View>

        <TouchableOpacity 
            onPress={handleGenerate}
            disabled={loading || !selectedResume || !selectedApp}
            className={`mt-10 h-16 rounded-[24px] flex-row items-center justify-center shadow-xl ${loading || !selectedResume || !selectedApp ? 'bg-slate-800' : 'bg-blue-600'}`}
        >
            {loading ? (
                <ActivityIndicator color="#fff" />
            ) : (
                <>
                    <FontAwesome name="magic" size={20} color="#fff" className="mr-3" />
                    <Text className="text-white font-bold text-lg italic">Generate Tailored LaTeX</Text>
                </>
            )}
        </TouchableOpacity>
        
        <View className="h-20" />
      </ScrollView>
    </SafeAreaView>
  );
}
